# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "AppsInToss CLI"
  homepage "https://toss.im"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.4.0/ax_darwin_arm64.tar.gz"
      sha256 "13b3510cab942746663a6197a85d92147392b6298a3508b8c128de271e738bf8"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.4.0/ax_darwin_amd64.tar.gz"
      sha256 "185fe5f8a44e0dea4a5ec039d182de76f4f6957a662afb14f6cf6e49ab784cfc"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.4.0/ax_linux_arm64.tar.gz"
      sha256 "1c30c735c0c0fb029b3edfe4817c5d347ceee93a70d443ca296537b5615787ee"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.4.0/ax_linux_amd64.tar.gz"
      sha256 "cde2dcc0806a0c5d7e959f32d998978e2080705a6fc007e7776ed5919e45ca0f"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end
end