# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "AppsInToss CLI"
  homepage "https://toss.im"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.7.1/ax_darwin_arm64.tar.gz"
      sha256 "5ba213b3db18441614de6e4de2d83c0ce8093a0e7e8176dd2115047a886f67bc"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.7.1/ax_darwin_amd64.tar.gz"
      sha256 "c985a7a828ba53b54e130f62bd23d3706009f1aa8abf341d245ae0c818e7df74"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.7.1/ax_linux_arm64.tar.gz"
      sha256 "158319e065d34cf7735ce68a6e386ddcaf9d1617394e4a44637f1e70adef732e"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.7.1/ax_linux_amd64.tar.gz"
      sha256 "f486ec6a22b0994807654038f930ea0e1674ed4eb08dab813f814e22d7fa2e1d"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end
end