# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "AppsInToss CLI"
  homepage "https://toss.im"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.2.2/ax_darwin_arm64.tar.gz"
      sha256 "787f39507ab43f73e381b932ef3b19eb3a3e1885998c8a4d8e2964719556990f"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.2.2/ax_darwin_amd64.tar.gz"
      sha256 "71545a898f6f584ae5dec4ed71b02a878d9a07194581b2f0db593dab60837923"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.2.2/ax_linux_arm64.tar.gz"
      sha256 "abeca05a646292d1c0ea9f1b05a64e41d2b3026bb86a912e84a944c05c2eef61"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/toss/apps-in-toss-ax/releases/download/v0.2.2/ax_linux_amd64.tar.gz"
      sha256 "67708eba487e7f1e73fa9cdfe776a828878de59f0fa0a4dac5fa47a2b1ce3252"

      def install
        bin.install "ax"
        (bash_completion/"ax").write `#{bin}/ax completion bash`
        (fish_completion/"ax.fish").write `#{bin}/ax completion fish`
        (zsh_completion/"_ax").write `#{bin}/ax completion zsh`
      end
    end
  end
end